

language: php

# optionally set up exclusions and allowed failures in the matrix
matrix:
  include:
  # Definicion de pruebas sobre multiples versiones de lenguaje y motor
  - php: 7.0
      dist: trusty
      env:
      - DB=pgsql
      sudo: required
      services:
      - postgresql
      
    - php: 7.1
      dist: trusty
      env:
      - DB=pgsql
      sudo: required
      services:
      - postgresql

    - php: 7.2
      dist: trusty
      env:
      - DB=pgsql
      sudo: required
      services:
      - postgresql

  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql
    - php: 7.0
    - php: hhvm

# extensiones
before_install:
 
addons: 
  apt: 
    packages: 
      - php-simplexml
      - php-mbstring
      - php-mcrypt
      - php-gd
      - php-zip
      - pdo-pgsql

script: "phpunit --configuration phpunit_$DB.xml --coverage-text"
services: 
  - postgresql
sudo: required
